[book]
authors = ["josh rotenberg"]
language = "en"
multilingual = false
src = "src"
title = "wtd-bayarea"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/joshrotenberg/wtd-bayarea-mdbook/tree/main"
edit-url-template = "https://github.com/joshrotenberg/wtd-bayarea-mdbook/edit/main/{path}"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2